#@PydevCodeAnalysisIgnore
from csmp import MACRO, TITLE, PARAM, CONSTANT, METHOD, TIMER, OUTPUT, PRINT
from csmp import EXP, AMIN1
from csmp import Clip


X = INTGRL(10., RX)
RX = 0.05*X

TITLE("DRY MATTER PRODUCTION")
TIMER(FINTIM = 100., DELT = 1., PRDEL = 7., OUTDEL = 5.)
#METHOD("RECT")
PRINT(X, RX, DELT)
OUTPUT(TWT)
